server:
  port: 8765
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routesMap:
            user-service:
              uri: lb://user-service
              predicates:
                - Path=/user/**, /user-service/v3/api-docs
              filters:
                - name: AddRequestHeader
                  args:
                      name: X-Test
                      values: user-service
          # (optional) trusted proxy setting
          trusted-proxies: 10\.0\.0\..*
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /user-service/v3/api-docs
        name: user-service