server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            user-service:
              uri: http://localhost:8080
              predicates:
                - Path=/user
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Gateway, MVC-Gateway