server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routesMap:
            user-service:
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - name: AddRequestHeader
                  args:
                      name: X-Test
                      values: user-service
          # (optional) trusted proxy setting
          trusted-proxies: 10\.0\.0\..*