server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/user/*
          uri: llb://user-service
        - id: second
          predicates:
            - Path=/second/
          uri: localhost:8082
        - id : auth-server
          predicates:
            - Path=/login/
          uri: localhost:8088